// <auto-generated />
namespace CAGLAR.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Customer2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Customer2));
        
        string IMigrationMetadata.Id
        {
            get { return "201906301931518_Customer2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
